Repository silverstripe/silverstripe-framework, pull requests merged in 2018-09, with the labels that each got.

#8358 FIX Check scheme is truthy before setting it to the request
  src/Control/CLIRequestBuilder.php
Labels: affects/v4, change/patch

#8318 3.7 HTTP Caching fixes
  admin/code/LeftAndMain.php
  security/Security.php
Labels: affects/v3, change/patch

#8360 Make sure that CMS requests disable caching
  src/Security/Security.php
Labels: affects/v4, change/patch

#8359 Add schema information for HTMLEditorField
  src/Forms/HTMLEditor/HTMLEditorConfig.php
  src/Forms/HTMLEditor/HTMLEditorField.php
  src/Forms/HTMLEditor/TinyMCEConfig.php
Labels: affects/v4, change/minor

#8372 Removed SS_CONFIGSTATICMANIFEST
  docs/en/00_Getting_Started/03_Environment_Management.md
Labels: affects/v4, type/docs

#8369 Update 01_Extensions.md - Fix small typo
  docs/en/02_Developer_Guides/05_Extending/01_Extensions.md
Labels: affects/v4, type/docs

#8361 Release process docs
  docs/en/05_Contributing/01_Code.md
  docs/en/05_Contributing/04_Release_Process.md
  docs/en/05_Contributing/05_Making_A_SilverStripe_Core_Release.md
Labels: affects/v4, type/docs

#8378 NEW Add hideNav flag to schema defaults
  src/Forms/TabSet.php
Labels: affects/v4, change/minor

#8348 Issue 3357 - Add GridField Readonly Transformation
  src/Forms/GridField/GridField.php
  src/Forms/GridField/GridFieldConfig_RecordViewer.php
  tests/php/Forms/GridField/GridFieldReadonlyTest.php
  tests/php/Forms/GridField/GridFieldReadonlyTest.yml
Labels: affects/v4, impact/critical, type/bug, type/frontend

#8394 BUG Prevent error on valid response status codes
  src/Control/HTTPResponse.php
  tests/php/Control/HTTPResponseTest.php
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/bug

#8400 FIX Revert semver break in adding GridField type hint to method signature
  src/Forms/GridField/GridFieldFilterHeader.php
Labels: affects/v4, change/patch

#8398 FIX Don't flush manifests in tests by default
  docs/en/02_Developer_Guides/06_Testing/index.md
  src/Dev/SapphireTest.php
Labels: affects/v4, change/minor, effort/medium, impact/high, type/bug

#8404 Typo in code snippet
  docs/en/02_Developer_Guides/02_Controllers/01_Introduction.md
Labels: affects/v4, type/docs

#8410 FormField::debug should handle all types of values
  src/Forms/FormField.php
Labels: affects/v4, change/patch

#8387 FIX: Ensure existing session can be accessed if headers_sent()
  src/Control/Session.php
Labels: affects/v4, change/patch

#8418 MINOR Reduce some code complexity, update array syntax and injected SQLSelect etc
  src/ORM/ArrayList.php
  src/ORM/DataList.php
  src/ORM/DataObject.php
  src/ORM/HasManyList.php
  src/ORM/ManyManyList.php
  src/ORM/ManyManyThroughList.php
  src/ORM/ManyManyThroughQueryManipulator.php
  src/ORM/PolymorphicHasManyList.php
  src/Security/Member_GroupSet.php
  src/View/ViewableData.php
Labels: affects/v4, change/minor

#8421 Update deprecation PHPDocs to be PSR-5 compliant
  src/Control/Controller.php
  src/Control/HTTP.php
  src/Control/RequestFilter.php
  src/Control/RequestProcessor.php
  src/Control/Session.php
  src/Control/SimpleResourceURLGenerator.php
  src/Core/ClassInfo.php
  src/Core/Extensible.php
  src/Core/Manifest/Module.php
  src/Dev/FunctionalTest.php
  src/Dev/Install/InstallEnvironmentAware.php
  src/Dev/SapphireTest.php
  src/Forms/FieldList.php
  src/Forms/GridField/GridFieldVersionedState.php
  src/Forms/HTMLEditor/TinyMCEConfig.php
  src/Forms/HTMLEditor/TinyMCEGZIPGenerator.php
  src/Forms/TreeDropdownField.php
  src/ORM/Connect/DBSchemaManager.php
  src/ORM/DataObject.php
  src/Security/LoginAttempt.php
  src/Security/Member.php
  src/Security/Security.php
  src/View/Requirements.php
  src/View/Requirements_Backend.php
  src/View/Requirements_Minifier.php
  src/View/SSViewer.php
  src/View/ViewableData.php
  src/conf/ConfigureFromEnv.php
  tests/php/Security/BasicAuthTest/ControllerNotSecured.php
Labels: affects/v4, change/minor

#8422 Update index.md
  docs/en/03_Upgrading/index.md
Labels: affects/v4, type/docs
