Repository silverstripe/silverstripe-framework, pull requests merged in 2018-08, with the labels that each got.

#8317 FIX txt/json is not a valid content type
  admin/code/LeftAndMain.php
  admin/javascript/LeftAndMain.js
  admin/tests/LeftAndMainTest.php
  control/PjaxResponseNegotiator.php
  tests/control/PjaxResponseNegotiatorTest.php
Labels: affects/v3, change/patch

#8321 Fix indentation on pagination guide
  docs/en/02_Developer_Guides/01_Templates/How_Tos/02_Pagination.md
Labels: affects/v4, type/docs

#8329 Update 07_Permissions.md
  docs/en/02_Developer_Guides/00_Model/07_Permissions.md
Labels: affects/v4, type/docs

#8330 convert to short array syntax
  src/Control/RequestHandler.php
Labels: affects/v4, change/patch

#8315 FIX Paginating a gridfield causing a change event
  src/Forms/GridField/GridFieldPaginator.php
Labels: affects/v4, change/patch

#8324 FIX Pass request to dummy controller before calling init
  src/Security/Security.php
Labels: affects/v4, change/patch

#8316 Password changing notification issue on new member
  src/Security/Member.php
Labels: affects/v4, change/patch

#8323 email rendering should not include requirements
  src/Control/Email/Email.php
Labels: affects/v4, change/patch

#8326 FIX Remove double escaping of HTML values in print views
  src/Forms/GridField/GridFieldPrintButton.php
Labels: affects/v4, change/patch

#8028 unset http scheme on CLIRequestBuilder
  src/Control/CLIRequestBuilder.php
Labels: affects/v4, change/patch

#8075 FIX Polymorphic relationship class columns have obsolete class names remapped
  src/ORM/DatabaseAdmin.php
Labels: affects/v4, change/patch

#8337 Allow use of display names with SwiftMailer
  docs/en/02_Developer_Guides/10_Email/index.md
Labels: affects/v4, effort/easy, impact/low, type/docs

#8351 BUG Use classes for TinyMCE alignment buttons
  src/Forms/HTMLEditor/TinyMCEConfig.php
Labels: affects/v4, change/patch
