Repository silverstripe/silverstripe-framework, pull requests merged in 2018-07, with the labels that each got.

#8200 Refactoring versioning doc
  docs/en/02_Developer_Guides/00_Model/10_Versioning.md
Labels: affects/v4, type/docs

#8231 MINOR: DataObject->fieldLabels() will only return an array
  src/ORM/DataObject.php
Labels: affects/v4, change/patch, type/docs

#8260 FIX Duplicate config values for cascade_duplicates no longer duplicate their duplicates
  src/ORM/DataObject.php
Labels: affects/v4, change/patch

#8263 FIX updateValidatePassword calls need to be masked from backtraces
  src/Dev/Backtrace.php
  tests/php/Dev/BacktraceTest.php
Labels: affects/v4, change/patch

#8213 FIX FormField::Link works when no form is currently set
  src/Forms/FormField.php
  tests/php/Forms/FormFieldTest.php
Labels: affects/v4, change/patch

#8270 FIX: Correct afterCallActionHandler arguments to match SS4.
  control/RequestHandler.php
Labels: affects/v3, change/patch

#8269 BUG Lazy session state (fixes #8267)
  src/Control/Director.php
  src/Control/Session.php
  src/Security/MemberAuthenticator/SessionAuthenticationHandler.php
  tests/php/Control/SessionTest.php
  tests/php/Security/MemberAuthenticator/SessionAuthenticationHandlerTest.php
Labels: affects/v4, change/patch, impact/high

#8274 Corrected caching docs and deprecation behaviour (fixes #8272)
  docs/en/02_Developer_Guides/08_Performance/02_HTTP_Cache_Headers.md
  src/Control/HTTP.php
  src/Control/Middleware/HTTPCacheControlMiddleware.php
  src/ORM/DataObject.php
  tests/php/Control/HTTPTest.php
  tests/php/Control/Middleware/HTTPCacheControlMiddlewareTest.php
Labels: affects/v4, change/patch

#8271 FIX Ensure tests pass by reducing to PHPUnit 7.1.3
  .editorconfig
  composer.json
  phpunit.xml.dist
  src/Control/HTTP.php
  src/Control/HTTPResponse.php
  src/Control/Middleware/HTTPCacheControlMiddleware.php
  tests/php/Core/Injector/InjectorTest.php
Labels: affects/v5, change/patch

#8282 Make removeDuplicates() chainable
  src/ORM/ArrayList.php
Labels: affects/v4, change/minor

#8287 Fix backtick in changelog breaking sentence formatting
  docs/en/04_Changelogs/4.2.0.md
Labels: affects/v4, type/docs

#8292 FIX Altering ID of authenticator tabs to resolve ID conflict
  templates/SilverStripe/Security/Security_MultiAuthenticatorTabbedForms.ss
Labels: affects/v4, change/patch
