Repository silverstripe/silverstripe-framework, pull requests merged in 2018-10, with the labels that each got.

#8409 MINOR Add caching to the TreeDropdownField tree action
  src/Forms/TreeDropdownField.php
Labels: affects/v4, change/minor

#8430 FIX: Don’t use USE_FRM in MySQL repair. Fixes #6300.
  src/ORM/Connect/MySQLSchemaManager.php
Labels: affects/v4, change/patch

#8414 FIX Avoid having search fields with the same names as form elements
  src/Forms/GridField/GridFieldFilterHeader.php
  tests/php/Forms/GridField/GridFieldFilterHeaderTest.php
Labels: affects/v4, change/patch

#8420 Add extension points for ModelAdmin search API
  src/Forms/GridField/GridFieldFilterHeader.php
Labels: affects/v4, change/minor

#8432 NEW: Add test for PHP 7.3 support (SS4 version)
  .travis.yml
Labels: affects/v4, change/patch

#8428 FIX: Don’t change state in ArrayList::getIterator()
  src/ORM/ArrayList.php
Labels: affects/v4, change/patch

#8423 FIX New members now receive the configured default locale, not the current locale
  src/Security/Member.php
  tests/php/Security/MemberTest.php
Labels: affects/v4, change/patch

#8408 Test cleanup
  .gitignore
  tests/php/Control/ControllerTest.php
  tests/php/Control/CookieJarTest.php
  tests/php/Control/CookieTest.php
  tests/php/Control/DirectorTest.php
  tests/php/Control/Email/EmailTest.php
  tests/php/Control/Email/SwiftMailerTest.php
  tests/php/Control/HTTPResponseTest.php
  tests/php/Control/HTTPTest.php
  tests/php/Control/PjaxResponseNegotiatorTest.php
  tests/php/Control/RequestHandlingTest.php
  tests/php/Control/SessionTest.php
  tests/php/Control/SimpleResourceURLGeneratorTest.php
Labels: affects/v4, change/patch

#8417 Add more list sorting tests and fix many many through sorting
  src/ORM/ManyManyThroughQueryManipulator.php
  tests/php/ORM/HasManyListTest.php
  tests/php/ORM/HasManyListTest.yml
  tests/php/ORM/HasManyListTest/CompanyCar.php
  tests/php/ORM/ManyManyThroughListTest.php
  tests/php/ORM/ManyManyThroughListTest/JoinObject.php
Labels: affects/v4, change/patch

#8446 FIX: Drop seconds from DBDatetime::Nice() to restore SS3 behaviour.
  src/ORM/FieldType/DBDatetime.php
  tests/php/ORM/DBDatetimeTest.php
Labels: affects/v4, change/patch

#8393 DOCS Add docs for CMS help menu links
  docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/How_Tos/Customise_CMS_Menu.md
  docs/en/05_Contributing/05_Making_A_SilverStripe_Core_Release.md
Labels: affects/v4, type/docs

#8303 Implement __isset for ViewableData_Customised
  src/View/ViewableData_Customised.php
  tests/php/View/ViewableDataCustomisedTest.php
Labels: affects/v4, change/patch

#8458 FIX: Don’t break validation on selects without a source.
  src/Forms/SingleSelectField.php
  tests/php/Forms/CompositeFieldTest.php
  tests/php/Forms/DropdownFieldTest.php
Labels: affects/v4, change/patch

#8451 NEW Add memory cache to ThemeResourceLoader::findTemplate()
  _config/cache.yml
  src/ORM/Connect/MySQLSchemaManager.php
  src/View/ThemeResourceLoader.php
  tests/php/Core/Manifest/ThemeResourceLoaderTest.php
Labels: affects/v4, change/minor

#8429 FIX: Throw deprecation on limit=0
  src/ORM/Queries/SQLSelect.php
  tests/php/ORM/SQLSelectTest.php
Labels: affects/v4, change/patch

#8463 FIX Remove unused cacheData prop from #8451
  src/View/ThemeResourceLoader.php
Labels: affects/v4, change/patch

#8440 NEW TabSet react component is no longer structural
  src/Forms/TabSet.php
Labels: affects/v4, change/minor

#8465 NEW Add method to flush extra_methods static cache data and implement into test state
  src/Core/Extensible.php
  src/Dev/State/ExtensionTestState.php
  tests/php/Core/Injector/InjectorTest.php
  tests/php/Core/Injector/InjectorTest/SomeCustomisedExtension.php
  tests/php/Core/Injector/InjectorTest/SomeExtension.php
Labels: affects/v4, change/minor

#8468 FIX Persist TinyMCE updates when writing with Behat
  tests/behat/src/CmsFormsContext.php
Labels: affects/v4, change/patch

#8437 FIX: Use DELETE FROM instead of TRUNCATE for clearTable
  src/ORM/Connect/MySQLDatabase.php
Labels: affects/v4, change/patch

#8435 FIX: Use DELETE FROM instead of TRUNCATE for clearTable
  model/connect/MySQLDatabase.php
  tests/model/DataObjectTest.php
Labels: affects/v3, change/patch

#8357 FIX Text collector translations now compile without errors
  lang/en.yml
  src/Forms/DateField_Disabled.php
Labels: affects/v4, change/patch

#8460 API Add a new GridFieldLazyLoader component
  docs/en/04_Changelogs/4.3.0.md
  src/Forms/CompositeField.php
  src/Forms/FieldList.php
  src/Forms/GridField/GridField.php
  src/Forms/GridField/GridFieldLazyLoader.php
  src/Forms/GridField/GridField_DataManipulator.php
  tests/php/Forms/CompositeFieldTest.php
  tests/php/Forms/FieldListTest.php
  tests/php/Forms/GridField/GridFieldLazyLoaderTest.php
Labels: affects/v4, change/minor

#8471 Example to override a value that is an array.
  docs/en/02_Developer_Guides/04_Configuration/00_Configuration.md
Labels: affects/v4, type/docs

#8439 FIX: Make ArrayList::limit() consistent with DataList::limit()
  src/ORM/ArrayList.php
  tests/php/ORM/ArrayListTest.php
Labels: affects/v4, change/minor

#8485 Update admin example code
  docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/02_CMS_Architecture.md
Labels: affects/v4, type/docs

#8486 BUG Gridfield pagination detected as form change
  templates/SilverStripe/Forms/GridField/GridFieldPaginator_Row.ss
Labels: affects/v4, change/patch

#8489 REGRESSION: TabSet no longer structural
  src/Forms/TabSet.php
Labels: affects/v4, change/patch

#8490 NEW Some minor refactoring of the PDO and MySQLi connectors
  src/ORM/Connect/MySQLiConnector.php
  src/ORM/Connect/PDOConnector.php
Labels: affects/v4, change/minor

#8495 BUGFIX #828 optimised query in graphql asset admin
  src/Security/InheritedPermissions.php
Labels: affects/v4, change/patch

#8502 [DOCUMENTATION] Correct name of author credit
  docs/en/04_Changelogs/3.7.0.md
Labels: affects/v3, type/docs

#8504 BUG: Fix enum filter in Search component adding `Any` as a filter
  src/ORM/FieldType/DBEnum.php
Labels: affects/v4, change/patch

#8505 FIX getExtensionInstance can return null, add a case to handle that
  src/Core/Extensible.php
  src/Dev/State/ExtensionTestState.php
Labels: affects/v4, change/patch

#8488 MINOR Update doc to explain how to use and build the pattern lib
  docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/02_CMS_Architecture.md
Labels: affects/v4, change/minor, effort/easy, impact/low, type/docs

#8477 Fix search filtering relations and clear filters
  src/Forms/GridField/GridFieldFilterHeader.php
Labels: affects/v4, change/patch

#8528 API Convert JSON methods are now deprecated, use json_encode or decode instead
  src/Control/PjaxResponseNegotiator.php
  src/Core/Convert.php
  src/Core/Manifest/VersionProvider.php
  src/Forms/FormRequestHandler.php
  src/Forms/GridField/GridFieldAddExistingAutocompleter.php
  src/Forms/GridField/GridFieldFilterHeader.php
  src/Forms/GridField/GridField_ActionMenu.php
  src/Forms/HTMLEditor/TinyMCEConfig.php
  src/ORM/FieldType/DBField.php
  tests/php/Forms/GridField/GridFieldAddExistingAutocompleterTest.php
  tests/php/Forms/HTMLEditor/HTMLEditorConfigTest.php
Labels: affects/v4, change/minor

#8539 Add missing deprecation notices to Convert json methods
  src/Core/Convert.php
Labels: affects/v4, change/minor
