Repository silverstripe/silverstripe-framework, pull requests merged in 2018-06, with the labels that each got.

#8101 FIX PHP 5.3 compat for referencing $this in closures
  security/Member.php
Labels: affects/v3, change/patch

#8130 Update 03_Requirements.md
  docs/en/02_Developer_Guides/01_Templates/03_Requirements.md
Labels: affects/v4, type/docs

#8129 Increase memory limit to 2G in Travis builds
  .travis.yml
Labels: affects/v3, change/patch

#8127 Fix: negative values in read only currency field
  src/Forms/CurrencyField_Disabled.php
  src/Forms/CurrencyField_Readonly.php
Labels: affects/v4, change/patch

#8095 ENHANCEMENT: Add new CacheProxy to segment versioned state
  cache/Cache.php
  cache/CacheProxy.php
  core/manifest/ConfigManifest.php
  core/manifest/SilverStripeVersionProvider.php
  docs/en/02_Developer_Guides/08_Performance/01_Caching.md
  docs/en/04_Changelogs/3.7.0.md
  filesystem/GD.php
  i18n/i18n.php
  tasks/CleanImageManipulationCache.php
  tests/cache/CacheTest.php
  tests/model/DataObjectDuplicationTest.php
  view/SSViewer.php
Labels: affects/v3, change/minor

#8132 FIX Regression from #8009
  tests/model/DataObjectDuplicationTest.php
Labels: affects/v3, change/patch

#8122 BUG Prevent stage querystring args during dev/build
  dev/DevelopmentAdmin.php
Labels: affects/v3, change/patch

#8124 FIX Minor updates to unit tests to pass with HTML5 parser and various themes
  tests/php/Forms/EmailFieldTest.php
  tests/php/Forms/FormTest.php
  tests/php/Forms/GridField/GridFieldDetailFormTest.php
  tests/php/Forms/LookupFieldTest.php
  tests/php/Forms/SelectionGroupTest.php
  tests/php/Forms/TreeDropdownFieldTest.php
Labels: affects/v4, change/patch, impact/low

#8106 DOCS Remove broken badges from readme: versioneye and helpfulrobot
  README.md
Labels: affects/v4, type/docs

#8109 Object upgrade notice for 3.7.0 changelog
  docs/en/04_Changelogs/3.7.0.md
Labels: affects/v3, type/docs

#8113 BUGFIX: Allow buttons to opt out of display
  src/Forms/GridField/GridFieldDeleteAction.php
  src/Forms/GridField/GridFieldGroupDeleteAction.php
  src/Forms/GridField/GridField_ActionMenu.php
  src/Forms/GridField/GridField_ActionMenuItem.php
  tests/php/Forms/GridField/GridFieldActionMenuTest.php
  tests/php/Forms/GridField/GridFieldConfigTest/MyActionMenuItemComponent.php
  tests/php/Forms/GridField/GridFieldDeleteActionTest.php
  tests/php/Forms/GridField/GridFieldGroupDeleteActionTest.php
  tests/php/Forms/GridField/GridFieldGroupDeleteActionTest.yml
Labels: affects/v4, change/patch

#8146 BUG Fix crash on ID in default_sort
  model/DataObject.php
  tests/model/DataObjectTest.php
Labels: affects/v3, change/patch, effort/easy, impact/high, type/bug

#8150 BUG Fix test that relies on implicit ID order breaking postgres
  src/Forms/HTMLEditor/HTMLEditorSanitiser.php
  src/ORM/Queries/SQLSelect.php
  src/View/Parsers/ShortcodeParser.php
  tests/php/ORM/DataObjectDuplicationTest.php
Labels: affects/v4, change/patch, effort/easy, impact/low, type/bug

#8089 FIX Add macron to Māori language name
  src/Dev/Install/InstallConfig.php
Labels: affects/v4, change/patch

#8102 Add test assertion for response instance
  tests/php/Control/DirectorTest.php
Labels: affects/v4, change/patch

#8142 BUG Safely handle empty injector factory responses
  src/Core/Injector/Injector.php
  tests/php/Core/Injector/InjectorTest.php
  tests/php/Core/Injector/InjectorTest/EmptyFactory.php
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug

#8158 BUG Prevent canonical URL causing a redirect on CLI unless explicitly enabled
  src/Control/Middleware/CanonicalURLMiddleware.php
Labels: affects/v4, change/patch, type/bug

#8160 BUG Error if invalid stage specified for get_by_stage
  model/Versioned.php
Labels: affects/v3, change/patch

#8165 BUG Remove duplicate key
  .upgrade.yml
Labels: affects/v4, change/patch

#8063 Batch action on Page loading screen fix
  admin/javascript/LeftAndMain.BatchActions.js
Labels: affects/v3, change/patch

#8177 FIX SapphireTest can load relative fixtures in subfolders, switch "needs db" priority check order
  src/Dev/SapphireTest.php
  src/Dev/State/FixtureTestState.php
Labels: affects/v4, change/patch

#8170 BUG Fix internal date formatting inheriting default locale
  src/Forms/DateField.php
  src/Forms/DatetimeField.php
  src/ORM/FieldType/DBDate.php
  src/ORM/FieldType/DBDatetime.php
  tests/php/Forms/DatetimeFieldTest.php
  tests/php/ORM/DBDatetimeTest.php
Labels: affects/v4, change/patch

#8181 API Remove @internal from new 4.2 methods
  src/ORM/FieldType/DBDate.php
  src/ORM/FieldType/DBDatetime.php
Labels: affects/v4, change/minor, effort/easy, impact/low, type/docs

#8183 Mention public folder in 4.0.0 upgrading overview
  docs/en/04_Changelogs/4.0.0.md
  docs/en/04_Changelogs/4.1.0.md
Labels: affects/v4, type/docs

#7949 Use LimitWordCount instead of LimitWordCountXML
  docs/en/01_Tutorials/04_Site_Search.md
Labels: affects/v4, change/patch

#8023 LookupField value handling corrected
  src/Forms/LookupField.php
  src/Forms/SingleLookupField.php
  src/Forms/SingleSelectField.php
  tests/php/Forms/SingleLookupFieldTest.php
Labels: affects/v4, change/minor, effort/medium, impact/medium, type/bug, type/enhancement

#8198 FIX Switch to Trusty in Travis
  .travis.yml
Labels: affects/v3

#8188 Tweaks on the ArrayLib class
  src/ORM/ArrayLib.php
Labels: affects/v4, change/minor, type/enhancement

#8192 FIX Add Embed dispatchers to be configured with injector
  src/View/Shortcodes/EmbedShortcodeProvider.php
Labels: affects/v4, change/patch

#8194 NEW Shift Embeddable and EmbedResource from asset-admin, lazy load Embed to allow injected dependencies
  .upgrade.yml
  _config/oembed.yml
  src/View/Embed/EmbedResource.php
  src/View/Embed/Embeddable.php
  src/View/Shortcodes/EmbedShortcodeProvider.php
  tests/php/View/Embed/EmbedResourceTest.php
Labels: affects/v4, change/minor

#8199 Ensure silverstripe/recipe-cms is installed from source during Travis builds
  .travis.yml
Labels: affects/v4, change/patch, impact/low

#8209 DOCS Vendor paths for test docs
  docs/en/02_Developer_Guides/06_Testing/index.md
Labels: affects/v4, type/docs

#8211 Correct path in $ModulePath example for templates
  docs/en/04_Changelogs/4.0.0.md
Labels: affects/v4, type/docs

#8229 Replace broken link to tutorial
  docs/en/02_Developer_Guides/03_Forms/00_Introduction.md
Labels: affects/v4, type/docs
