Repository silverstripe/silverstripe-framework, pull requests merged in 2018-04, with the labels that each got.

#7982 Fix invalid markup in SelectionGroup selected values
  templates/SilverStripe/Forms/SelectionGroup.ss
  tests/php/Forms/SelectionGroupTest.php
Labels: affects/v4, change/patch

#7989 BUG Fix many_many through crashing ModelAdmin
  src/Dev/BulkLoader.php
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug

#7990 README fix contributing-link, add httpS
  README.md
Labels: affects/v3, type/docs

#7994 Update some phpdocs that had typos, missing parts or incorrect formats
  admin/code/CMSBatchAction.php
  admin/code/CMSMenu.php
  admin/code/LeftAndMain.php
  core/ArrayLib.php
  core/Config.php
  core/Extension.php
  core/Object.php
  core/manifest/ConfigManifest.php
  filesystem/Upload.php
  forms/DropdownField.php
  forms/FieldList.php
  forms/FileField.php
  forms/FormField.php
  forms/FormScaffolder.php
  forms/HtmlEditorConfig.php
  forms/HtmlEditorSanitiser.php
  forms/SelectionGroup.php
  forms/TreeDropdownField.php
  forms/UploadField.php
  forms/gridfield/GridFieldAddExistingAutocompleter.php
  forms/gridfield/GridFieldComponent.php
  forms/gridfield/GridFieldDataColumns.php
  forms/gridfield/GridFieldFooter.php
  forms/gridfield/GridFieldPageCount.php
  forms/gridfield/GridFieldSortableHeader.php
  forms/gridfield/GridState.php
  parsers/ShortcodeParser.php
  security/BasicAuth.php
  security/Group.php
  security/MemberLoginForm.php
  security/PasswordEncryptor.php
Labels: affects/v3, change/patch

#8007 API Form::makeReadonly() returns self
  src/Forms/Form.php
Labels: affects/v4, change/minor

#8017 Fix a broken link to the versioning page
  docs/en/02_Developer_Guides/00_Model/02_Relations.md
Labels: affects/v4, type/docs

#8034 Document requirements for Configurable trait
  docs/en/02_Developer_Guides/04_Configuration/00_Configuration.md
Labels: affects/v4, type/docs

#8013 BUG Prevent password validator min score producing false negatives
  src/Security/PasswordValidator.php
  tests/php/Security/MemberTest/TestPasswordValidator.php
  tests/php/Security/PasswordValidatorTest.php
Labels: affects/v4, change/patch, effort/easy, impact/low, type/bug
