Repository silverstripe/silverstripe-framework, pull requests merged in 2018-03, with the labels that each got.

#7887 Allow PHPParser v4
  composer.json
Labels: affects/v5

#7894 get_by_id: alternate signature to allow MyDataObject::get_by_id($id)
  src/ORM/DataObject.php
  tests/php/ORM/DataObjectTest.php
Labels: affects/v4, change/minor

#7907 TestCase classes should be abstract to prevent warnings
  src/Dev/FunctionalTest.php
  src/Dev/SapphireTest.php
Labels: affects/v5

#7908 DOCS Fix reference to force_resample
  docs/en/02_Developer_Guides/14_Files/02_Images.md
Labels: affects/v4, type/docs

#7603 ENHANCEMENT Don't infer trace if explicitly provided
  src/Logging/DetailedErrorFormatter.php
Labels: affects/v4, change/patch, effort/easy, impact/high, type/enhancement

#7914 BUG Files dataobjects with missing asset shouldn't un-attach themselves on save
  src/Forms/FileUploadReceiver.php
Labels: affects/v4, change/patch, effort/easy, impact/low, type/bug

#7912 DOCS Fix API references for classes in versioning docs
  docs/en/02_Developer_Guides/00_Model/10_Versioning.md
Labels: affects/v4, type/docs

#7919 DOCS add missing trailing ; in code block
  docs/en/02_Developer_Guides/02_Controllers/05_Middlewares.md
Labels: affects/v4, type/docs

#7921 Add missing use statement in Session documentation
  docs/en/02_Developer_Guides/18_Cookies_And_Sessions/02_Sessions.md
Labels: affects/v4, type/docs

#7924 Remove Hamish, Stig, Sean, Jono from core committers :(
  docs/en/05_Contributing/09_Core_committers.md
Labels: type/docs

#7925 Add Paul to core designers team
  docs/en/05_Contributing/09_Core_committers.md
Labels: feedback-required/core-team, type/docs

#7875 Suggested feature: dev/build record count
  src/ORM/DatabaseAdmin.php
Labels: affects/v4, change/minor

#7927 Fixing FormAction API documentation
  forms/FormAction.php
Labels: affects/v3, change/patch, type/docs

#6518 Use Generators for ORM Query, Map, ArrayList
  docs/en/04_Changelogs/5.0.0.md
  src/ORM/ArrayList.php
  src/ORM/Connect/DBSchemaManager.php
  src/ORM/Connect/MySQLQuery.php
  src/ORM/Connect/MySQLStatement.php
  src/ORM/Connect/PDOQuery.php
  src/ORM/Connect/Query.php
  src/ORM/DataList.php
  src/ORM/ManyManyList.php
  src/ORM/Map.php
  src/ORM/Map_Iterator.php
  src/ORM/PaginatedList.php
  src/View/SSViewer_Scope.php
  tests/php/ORM/DatabaseTest.php
  tests/php/ORM/MySQLDatabaseTest.php
  tests/php/ORM/PDODatabaseTest.php
  tests/php/ORM/PaginatedListTest.php
Labels: affects/v4, change/major, impact/medium, type/enhancement

#7858 Add support.md file
  SUPPORT.md
Labels: affects/v3, type/docs

#7967 Reorder HTML to be semantically correct on render
  templates/SilverStripe/Forms/SelectionGroup.ss
Labels: affects/v4, change/patch
