Repository silverstripe/silverstripe-framework, pull requests merged in 2018-11, with the labels that each got.

#8534 BUGFIX many many through not sorting by join table
  docs/en/02_Developer_Guides/00_Model/02_Relations.md
  src/ORM/DataObject.php
  src/ORM/ManyManyThroughQueryManipulator.php
  tests/php/ORM/ManyManyListTest.php
  tests/php/ORM/ManyManyThroughListTest.php
  tests/php/ORM/ManyManyThroughListTest.yml
  tests/php/ORM/ManyManyThroughListTest/FallbackLocale.php
  tests/php/ORM/ManyManyThroughListTest/Locale.php
Labels: affects/v4

#8573 Convert::memstring2bytes should preserve -1
  src/Core/Convert.php
  tests/php/Core/ConvertTest.php
Labels: affects/v4, change/patch

#8560 NEW Deprecate RandomGenerator::generateEntropy in favour of using random_bytes directly
  src/Security/RandomGenerator.php
Labels: affects/v4, change/minor

#8514 FIX use Injector for FormField::castedCopy
  src/Forms/FormField.php
  src/Forms/TreeDropdownField_Readonly.php
Labels: affects/v4, change/patch

#8583 Convert::memstring2bytes should return integer value
  src/Core/Convert.php
  tests/php/Core/ConvertTest.php
Labels: affects/v4, change/patch

#8584 Cleanup Convert
  src/Core/Convert.php
  tests/php/Core/ConvertTest.php
Labels: affects/v4, change/minor

#8499 FIX: CheckboxSetField can now save into DBMultiEnum
  src/Forms/MultiSelectField.php
  tests/php/Forms/CheckboxFieldtest/MutiEnumArticle.php
  tests/php/Forms/CheckboxSetFieldMultiEnumTest.php
Labels: affects/v4, change/patch

#8506 NEW Adding a stack more unit tests for logging and some form fields
  src/Control/Director.php
  src/Forms/CompositeField.php
  src/Forms/ConfirmedPasswordField.php
  src/Forms/CurrencyField.php
  src/Forms/CurrencyField_Disabled.php
  src/Forms/CurrencyField_Readonly.php
  src/Forms/DateField.php
  src/Forms/DefaultFormFactory.php
  src/Forms/PrintableTransformation_TabSet.php
  src/Forms/TabSet.php
  src/Logging/DebugViewFriendlyErrorFormatter.php
  src/Logging/DetailedErrorFormatter.php
  src/Logging/HTTPOutputHandler.php
  src/Logging/MonologErrorHandler.php
  src/ORM/ListDecorator.php
  tests/php/Forms/CheckboxFieldReadonlyTest.php
  tests/php/Forms/CompositeFieldTest.php
  tests/php/Forms/ConfirmedPasswordFieldTest.php
  tests/php/Forms/CurrencyFieldDisabledTest.php
  tests/php/Forms/CurrencyFieldReadonlyTest.php
  tests/php/Forms/CurrencyFieldTest.php
  tests/php/Forms/DatalessFieldTest.php
  tests/php/Forms/DateFieldDisabledTest.php
  tests/php/Forms/DateFieldTest.php
  tests/php/Forms/DatetimeFieldTest.php
  tests/php/Forms/DefaultFormFactoryTest.php
  tests/php/Forms/DisabledTransformationTest.php
  tests/php/Forms/PrintableTransformationTabSetTest.php
  tests/php/Forms/PrintableTransformationTest.php
  tests/php/Logging/DebugViewFriendlyErrorFormatterTest.php
  tests/php/Logging/DetailedErrorFormatterTest.php
  tests/php/Logging/HTTPOutputHandlerTest.php
  tests/php/Logging/MonologErrorHandlerTest.php
  tests/php/ORM/ListDecoratorTest.php
Labels: affects/v4, change/minor

#8587 FIX Move password complexity requirements into framework
  _config/passwords.yml
Labels: affects/v4, change/patch

#8601 FIX Remove default password validation rules before running unit tests
  tests/php/Security/PasswordValidatorTest.php
Labels: affects/v4, change/patch

#8604 FIX Ensure that tests setting passwords have stubbed configuration
  tests/php/Forms/ConfirmedPasswordFieldTest.php
  tests/php/Security/MemberTest.php
Labels: affects/v4, change/patch

#8610 FIX: Redirect loop with multiple confirmation tokens present (fixes #8607)
  src/Core/Startup/ConfirmationTokenChain.php
  tests/php/Core/Startup/ConfirmationTokenChainTest.php
  tests/php/Core/Startup/ErrorControlChainMiddlewareTest.php
Labels: affects/v4, change/patch

#8611 FIX: Redirect loop with multiple URL tokens (fixes #8607)
  core/startup/ConfirmationTokenChain.php
  tests/core/startup/ConfirmationTokenChainTest.php
Labels: affects/v3, change/patch

#8606 DOCS Add documentation for configuring a HistoryViewerField for custom DataObjects
  docs/en/02_Developer_Guides/00_Model/10_Versioning.md
  docs/en/04_Changelogs/4.3.0.md
Labels: affects/v4, type/docs

#8616 DOCS Updating HistoryViewer documentation to specify the rollback mutation instead of copyToStage
  docs/en/02_Developer_Guides/00_Model/10_Versioning.md
Labels: affects/v4, type/docs

#8629 renderWith() - Namespace added for Template Loading
  docs/en/02_Developer_Guides/01_Templates/How_Tos/03_Disable_Anchor_Links.md
Labels: affects/v4, type/docs

#8621 FIX Explicity mark nodes when searching
  src/Forms/TreeDropdownField.php
  tests/php/Forms/TreeDropdownFieldTest.php
  tests/php/Forms/TreeDropdownFieldTest.yml
Labels: affects/v4, change/patch

#8581 FIX Reverting ExtensionTestState and Extensible extra methods modifications to prevent PHP 5.6 segfault
  docs/en/02_Developer_Guides/05_Extending/01_Extensions.md
  docs/en/04_Changelogs/4.3.0.md
  src/Core/Extensible.php
  src/Dev/State/ExtensionTestState.php
  tests/php/Core/Injector/InjectorTest.php
  tests/php/Core/Injector/InjectorTest/SomeCustomisedExtension.php
  tests/php/Core/Injector/InjectorTest/SomeExtension.php
Labels: affects/v4, change/patch

#8633 Referencing env vars in configs
  docs/en/00_Getting_Started/03_Environment_Management.md
Labels: affects/v4, type/docs

#8646 ModelAdmin Menu Icon Class Documentation Added + Namespace Permissions
  docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/01_ModelAdmin.md
Labels: affects/v4, type/docs
