Repository silverstripe/silverstripe-framework, pull requests merged in 2019-03, with the labels that each got.

#8793 Throw error message when searchable_field does not return a object
  src/ORM/DataObject.php
Labels: affects/v4, change/minor

#8647 Documentation / update Server Requirements
  docs/en/00_Getting_Started/00_Server_Requirements.md
  docs/en/04_Changelogs/4.4.0.md
Labels: affects/v4, change/minor, feedback-required/core-team, impact/medium, type/docs

#8863 Update 00_CSV_Import.md
  docs/en/02_Developer_Guides/11_Integration/00_CSV_Import.md
Labels: affects/v4, type/docs

#8849 FIX: RequestHandler::__construct() should run after middlewares (fixes #8848)
  src/Control/Director.php
Labels: affects/v4, change/patch

#8847 Add option to leave Temp DB when exiting
  src/ORM/Connect/TempDatabase.php
Labels: affects/v4, change/minor

#8866 API Allow empty arraylists to be typed
  src/ORM/ArrayList.php
  tests/behat/src/CmsUiContext.php
  tests/php/Control/SimpleResourceURLGeneratorTest.php
  tests/php/Core/Manifest/ModuleResourceTest.php
  tests/php/ORM/ArrayListTest.php
Labels: affects/v4, change/minor, effort/easy, impact/low, type/enhancement

#8878 Update 02_RSSFeed.md
  docs/en/02_Developer_Guides/11_Integration/02_RSSFeed.md
Labels: affects/v4, type/docs
