Repository silverstripe/silverstripe-framework, pull requests merged in 2019-09, with the labels that each got.

#9200 FIX make the grid field actions consistent to what they look like on pages
  src/Forms/GridField/GridFieldDetailForm_ItemRequest.php
Labels: affects/v4, change/patch

#9164 FIX: Write relations when saving in grid-field item edit form
  src/Forms/GridField/GridFieldDetailForm_ItemRequest.php
Labels: affects/v4, change/patch

#9206 FIX Byte Order Marks (BOM) are now stripped when importing CSV files
  src/Dev/CsvBulkLoader.php
  tests/php/Dev/CsvBulkLoaderTest.php
  tests/php/Dev/CsvBulkLoaderTest/csv/PlayersWithHeaderAndBOM.csv
Labels: affects/v4, change/patch

#9122 Add onBeforeRenderHolder extension point for FormField
  src/Forms/FormField.php
Labels: affects/v4, change/minor

#9217 Update recommended node version in contrib docs
  docs/en/05_Contributing/02_Build_Tooling.md
Labels: affects/v4, type/docs

#9085 Catch Path::join() exceptions in findTemplate() (fixes #9084)
  src/View/ThemeResourceLoader.php
Labels: affects/v4, change/patch

#9226 FIX Member::getLastName() now correctly returns the Member surname
  src/Security/Member.php
  tests/php/Security/MemberTest.php
Labels: affects/v4, change/patch

#9229 Update secure coding standards
  docs/en/02_Developer_Guides/09_Security/04_Secure_Coding.md
Labels: affects/v4, type/docs

#9202 DOC Explain how to mgirate SS3.2 variants
  docs/en/02_Developer_Guides/14_Files/05_File_Migration.md
Labels: affects/v4, type/docs

#9207 ENH PasswordExpirationMiddleware implementation
  _config/security.yml
  docs/en/04_Changelogs/4.5.0.md
  src/Security/MemberAuthenticator/CMSLoginHandler.php
  src/Security/MemberAuthenticator/LoginHandler.php
  src/Security/PasswordExpirationMiddleware.php
  tests/php/Security/PasswordExpirationMiddlewareTest.php
Labels: affects/v4, change/minor

#9221 BUG Allow infinite loop when calling DataObject::writeComponent() recursively
  src/ORM/DataObject.php
  tests/php/ORM/DataObjectTest.php
  tests/php/ORM/DataObjectTest.yml
  tests/php/ORM/DataObjectTest/TreeNode.php
Labels: affects/v4, change/patch, feedback-required/author

#9181 NEW: Use templates to render embed shortcodes (closes #8762)
  src/View/Shortcodes/EmbedShortcodeProvider.php
  templates/SilverStripe/View/Shortcodes/EmbedShortcodeProvider_link.ss
  templates/SilverStripe/View/Shortcodes/EmbedShortcodeProvider_photo.ss
  templates/SilverStripe/View/Shortcodes/EmbedShortcodeProvider_video.ss
  tests/php/View/Shortcodes/EmbedShortcodeProviderTest.php
Labels: affects/v4, change/minor

#9153 FIX Skip md5-ing the whole contents of a stream for etags
  src/Control/Middleware/ChangeDetectionMiddleware.php
Labels: affects/v4, change/patch

#9169 Update 04_Create_a_GridField_ActionProvider.md
  docs/en/02_Developer_Guides/03_Forms/How_Tos/04_Create_a_GridField_ActionProvider.md
Labels: affects/v4, feedback-required/author, type/docs

#9248 Allow non summary fields to be used as grid field export fields
  src/Forms/GridField/GridFieldExportButton.php
Labels: affects/v4, change/patch

#9241 Fix administrators not being able to see files that are restricted to groups
  src/Security/InheritedPermissions.php
  tests/php/Security/InheritedPermissionsTest.php
  tests/php/Security/InheritedPermissionsTest.yml
Labels: affects/v4, change/patch

#9263 DOC Add warning about Semver status of modern JS / GraphQL tooling
  docs/en/02_Developer_Guides/15_Customising_the_Admin_Interface/07_ReactJS_Redux_and_GraphQL.md
Labels: affects/v4, type/docs
