Repository silverstripe/silverstripe-framework, pull requests merged in 2019-10, with the labels that each got.

#9247 ENHANCEMENT: MemberAuthenticator::recordLoginAttempt() outputs
  src/Security/MemberAuthenticator/MemberAuthenticator.php
Labels: affects/v4, change/minor

#9271 FIX Check array keys existence when removing methods in CustomMethods
  src/Core/CustomMethods.php
Labels: affects/v4, change/patch

#9275 FIX DebugViewFrendlyErrorFormatter handle of admin_email
  src/Control/Email/Email.php
  src/Logging/DebugViewFriendlyErrorFormatter.php
  tests/php/Logging/DebugViewFriendlyErrorFormatterTest.php
Labels: affects/v4, change/patch

#9287 Fix warnings/deprecations raised in PHP 7.4
  email/Email.php
  forms/Form.php
  i18n/i18n.php
  model/fieldtypes/Text.php
Labels: affects/v3, change/patch

#9292 Update Test documentation about test database behaviours
  docs/en/02_Developer_Guides/06_Testing/00_Unit_Testing.md
Labels: affects/v4, type/docs

#9310 DOC Describe our current branch naming conventions
  docs/en/05_Contributing/01_Code.md
Labels: affects/v4, type/docs

#9011 With config functionality added.
  docs/en/02_Developer_Guides/04_Configuration/00_Configuration.md
  src/Core/Config/Config.php
  tests/php/Core/Config/ConfigTest.php
Labels: affects/v4, change/minor
