Repository silverstripe/silverstripe-framework, pull requests merged in 2019-05, with the labels that each got.

#8952 FIX Don't add "better buttons" previous and next without a paginator
  src/Forms/GridField/GridFieldDetailForm_ItemRequest.php
Labels: affects/v4, change/patch

#8953 API Replace FormActions with anchors to enable panel-based loading in GridField navigation buttons
  lang/en.yml
  src/Forms/GridField/GridFieldDetailForm_ItemRequest.php
Labels: affects/v4, change/major

#8957 FIX Ensuring pagination buttons have a consistent state to work off of
  src/Forms/GridField/GridFieldDetailForm_ItemRequest.php
Labels: affects/v4, change/patch

#8969 Update docs for GridField_ActionMenuItem required parameters
  docs/en/02_Developer_Guides/03_Forms/How_Tos/04_Create_a_GridField_ActionProvider.md
Labels: affects/v4, type/docs

#8967 Commenting out the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: affects/v5, type/docs

#8976 FIX password validation min length message
  src/Security/PasswordValidator.php
Labels: affects/v4, change/patch

#8854 NEW: Add PHP 7.4’s daily snapshot to the travis suite.
  .travis.yml
Labels: affects/v4

#8855 NEW: Add PHP 7.4’s daily snapshot to the travis suite (SS 3.7)
  .travis.yml
Labels: affects/v3

#8981 Fix link to es6features
  docs/en/05_Contributing/02_Build_Tooling.md
Labels: affects/v4, type/docs

#8982 Fix link to related lesson
  docs/en/02_Developer_Guides/01_Templates/06_Themes.md
Labels: affects/v4, type/docs

#8984 NEW Adding a shuffle method to ArrayList
  src/ORM/ArrayList.php
  src/ORM/DataList.php
  tests/php/ORM/ArrayListTest.php
  tests/php/ORM/DataListTest.php
Labels: affects/v4, change/minor, feedback-required/core-team

#8979 Add extend function in getSchemaValidation function
  src/Forms/FormField.php
Labels: affects/v4, change/patch

#8983 DOCS Clarify CVE process
  docs/en/05_Contributing/05_Making_A_SilverStripe_Core_Release.md
Labels: affects/v4, type/docs

#9000 DOCS Update "release numbering" to document the fact that lock step releases are not required
  docs/en/05_Contributing/04_Release_Process.md
  docs/en/05_Contributing/05_Making_A_SilverStripe_Core_Release.md
Labels: affects/v4, type/docs

#9003 API: Drop PHP 5.6 and PHP 7.0 support in SS 4.5
  .travis.yml
  composer.json
  docs/en/00_Getting_Started/00_Server_Requirements.md
Labels: affects/v4, change/minor

#9002 DOCS Clarified file permission control
  docs/en/02_Developer_Guides/00_Model/10_Versioning.md
  docs/en/02_Developer_Guides/14_Files/01_File_Management.md
  docs/en/02_Developer_Guides/14_Files/03_File_Security.md
Labels: affects/v4, type/docs

#9007 FIX HeaderField requires the optional Title field
  src/Forms/HeaderField.php
Labels: affects/v4, change/patch

#9014 FIX: List default items in the readonly view of ListboxField
  src/Forms/MultiSelectField.php
  tests/php/Forms/ListboxFieldTest.php
  tests/php/Forms/ListboxFieldTest/Tag.php
Labels: affects/v4, change/patch

#8995 Show message when done.
  src/Dev/Tasks/MigrateFileTask.php
Labels: affects/v4, change/minor

#9025 Removed unused use BadMethodCallException statement.
  src/Dev/Install/Installer.php
Labels: affects/v4, change/minor

#9008 API checkHistoricalPasswords(), characterStrength() and minLength() are now correctly deprecated from 4.5.0 onwards
  docs/en/04_Changelogs/4.5.0.md
  src/Security/PasswordValidator.php
Labels: affects/v4, change/minor
