Repository silverstripe/silverstripe-framework, pull requests merged in 2019-01, with the labels that each got.

#8701 Update Travis to use PHP 7.3 stable
  .travis.yml
Labels: affects/v4, change/patch, impact/low

#8702 SS_Object::removeMethodsFrom silence notices
  core/Object.php
Labels: affects/v3, change/patch

#8703 CustomMethods->removeMethodsFrom Warnings
  src/Core/CustomMethods.php
Labels: affects/v4, change/patch

#8705 DOCS Retroactively apply proposed change to vendor-expose doc
  docs/en/02_Developer_Guides/01_Templates/03_Requirements.md
Labels: affects/v4, type/docs

#8709 Add documentation for additional file types
  docs/en/02_Developer_Guides/14_Files/01_File_Management.md
Labels: affects/v4, type/docs

#8722 fix [Warning] on count() with PHP >= 7.2
  model/Versioned.php
Labels: affects/v3, change/patch

#8725 Corrected `legacy_paths` to `legacy_filenames`
  docs/en/04_Changelogs/4.0.0.md
Labels: affects/v4, type/docs

#8717 BUG Fix issue with assertListEquals() ignoring field getters
  src/Dev/Constraint/ViewableDataContains.php
  tests/php/Dev/ViewableDataContainsTest.php
  tests/php/Dev/ViewableDataContainsTest/TestObject.php
Labels: affects/v4, change/patch

#8751 Update 03_Form_Templates.md - form template locations
  docs/en/02_Developer_Guides/03_Forms/03_Form_Templates.md
Labels: affects/v4, type/docs

#8755 Fix tests not loading fixtures and loading themes in CWP recipe kitchen sink
  tests/php/Forms/TreeMultiselectFieldTest.php
Labels: affects/v4, change/patch

#8743 fix user feedback when jquery could not be loaded
  src/Dev/Install/Installer.php
Labels: affects/v4, change/patch

#8763 Replace self:: with static:: for shortcode methods
  src/View/Shortcodes/EmbedShortcodeProvider.php
Labels: affects/v4, change/minor

#8729 Ensure document is not falsey before attempting to clone it
  src/View/Parsers/HTMLValue.php
  tests/php/View/Parsers/HTML4ValueTest.php
Labels: affects/v4, change/patch

#8761 explain resource url usage for add_i18n_javascript
  docs/en/02_Developer_Guides/13_i18n/index.md
Labels: affects/v4, type/docs

#8667 FIX: prevent shortcodeparser warnings when sitetree link includes anchors or querystrings
  src/View/Parsers/ShortcodeParser.php
  tests/php/View/Parsers/ShortcodeParserTest.php
Labels: affects/v4, change/patch

#8747 FIX: Injector may instantiate prototypes as if they're singletons (fixes #8567)
  control/injector/Injector.php
  tests/model/DataObjectTest.php
Labels: affects/v3, change/patch

#8558 API Deprecating Permission::$declared_permissions and related methods/props
  .upgrade.yml
  src/Security/Permission.php
Labels: affects/v4, change/minor
