Repository silverstripe/silverstripe-framework, pull requests merged in 2019-08, with the labels that each got.

#9159 NEW HTTPRequest now has hasSession() to determine whether a session exists for it
  src/Control/HTTPRequest.php
  src/Security/Security.php
  tests/php/Control/HTTPRequestTest.php
Labels: affects/v4, change/minor

#9173 FIX Use content generated by DataColumns component for print and csv export
  src/Forms/GridField/GridFieldExportButton.php
  src/Forms/GridField/GridFieldPrintButton.php
Labels: affects/v4, change/patch

#9177 FIX Member::changePassword() no longer applies password validation rules to the hashed value
  src/Security/Member.php
  tests/php/Security/MemberTest.php
  tests/php/Security/MemberTest/TestPasswordValidator.php
  tests/php/Security/MemberTest/VerySpecificPasswordValidator.php
Labels: affects/v4, change/patch

#9193 DOCS Remove Lighty docs
  docs/en/00_Getting_Started/01_Installation/How_To/Configure_Lighttpd.md
  docs/en/00_Getting_Started/index.md
Labels: affects/v4, type/docs

#9196 FIX Member argument is now passed to LeftAndMain::alternateAccessCheck()
  admin/code/LeftAndMain.php
Labels: affects/v3, change/patch

#9198 Bug : Add html_entity_decode to group parents
  src/Security/Group.php
Labels: affects/v4, change/patch

#9205 Add missing upgrade rules for Email class
  .upgrade.yml
Labels: affects/v4, change/patch
