Repository silverstripe/silverstripe-framework, pull requests merged in 2019-07, with the labels that each got.

#9100 Allow extensions to modify form scaffolder in DataObject
  src/ORM/DataObject.php
Labels: affects/v4, change/patch

#9070 FIX: Email::render() generating object instead of string for plaintext part (fixes #9069)
  src/Control/Email/Email.php
Labels: affects/v4, change/patch

#9105 NEW DBDate and DBDatetime now support modify() with a strtotime() style adjustment string
  src/ORM/FieldType/DBDate.php
  tests/php/ORM/DBDateTest.php
  tests/php/ORM/DBDatetimeTest.php
Labels: affects/v4, change/minor

#9074 FIX Confirmation components to respect SS_BASE_URL
  src/Control/Middleware/ConfirmationMiddleware.php
  src/Control/Middleware/URLSpecialsMiddleware.php
  src/Security/Confirmation/Storage.php
  tests/php/Control/Middleware/ConfirmationMiddlewareTest.php
  tests/php/Security/Confirmation/StorageTest.php
Labels: affects/v4, change/patch

#9052 NEW: Deprecated PDO in favour of native drivers
  _register_database.php
  src/Dev/Install/InstallConfig.php
  src/ORM/Connect/PDOConnector.php
Labels: affects/v4, change/minor

#9112 DOCS Add silverstripe/login-forms
  docs/en/02_Developer_Guides/09_Security/03_Authentication.md
  docs/en/04_Changelogs/4.5.0.md
Labels: affects/v4, type/docs

#9135 Added link to broaden description on SSL sertificates
  docs/en/00_Getting_Started/01_Installation/How_To/MySQL_SSL_Support.md
Labels: affects/v4, type/docs

#9138 #9114 - DBText::ContextSummary() cuts line breaks
  src/ORM/FieldType/DBText.php
  tests/php/ORM/DBHTMLTextTest.php
Labels: affects/v4, change/patch

#9110 BUG Require a PHP7.4 compatible fork of phpunit-mock-objects
  .travis.yml
  composer.json
  docs/en/04_Changelogs/3.7.4.md
  filesystem/GD.php
Labels: affects/v3, change/patch

#9139 Added SRI support for Requirements::css, Requirements::javascript
  src/View/Requirements.php
  src/View/Requirements_Backend.php
  tests/php/View/RequirementsTest.php
Labels: affects/v4, change/minor

#9152 FIX Prevent setting session value when no session exists yet
  src/Security/Security.php
Labels: affects/v4, change/patch
