Repository silverstripe/silverstripe-framework, pull requests merged in 2019-06, with the labels that each got.

#9036 URLSegmentFilter: Remove : characters from url segments when multibyt…
  src/View/Parsers/URLSegmentFilter.php
  tests/php/ORM/URLSegmentFilterTest.php
Labels: affects/v4, change/minor

#9039 Introduce static analysis
  .upgrade.yml
  src/Control/IPUtils.php
  src/Control/Middleware/TrustedProxyMiddleware.php
  src/Core/Manifest/ClassManifest.php
  src/Dev/DebugView.php
  src/Dev/Install/InstallRequirements.php
  src/Forms/ConfirmedPasswordField.php
  src/Forms/FormField.php
  src/Forms/GridField/GridField_ActionMenuLink.php
  src/Forms/NullableField.php
  src/ORM/Connect/MySQLDatabase.php
  src/ORM/Connect/MySQLSchemaManager.php
  src/ORM/DatabaseAdmin.php
  src/ORM/FieldType/DBBigInt.php
  src/ORM/FieldType/DBLocale.php
  src/View/Parsers/ShortcodeParser.php
  src/View/ThemeManifest.php
  tests/php/Control/IPUtilsTest.php
Labels: affects/v5, change/major

#9019 Including canCreate in if statement so that button gets removed if us…
  src/Forms/GridField/GridFieldDetailForm_ItemRequest.php
Labels: affects/v4, change/patch

#9012 FIX: Fix bug when confirmed password is changed but not the password.
  src/Forms/ConfirmedPasswordField.php
  tests/php/Forms/ConfirmedPasswordFieldTest.php
Labels: affects/v4, change/patch

#9048 [DOC] Minor revision, broken link
  docs/en/02_Developer_Guides/00_Model/08_SQL_Select.md
Labels: affects/v4, type/docs

#9050 DOCS: Add React 16 information
  docs/en/04_Changelogs/4.4.0.md
Labels: affects/v4, type/docs

#9010 NEW: Drop PHP 7.1 in SS5 (master)
  .travis.yml
  composer.json
  docs/en/00_Getting_Started/00_Server_Requirements.md
Labels: affects/v4, change/minor

#9081 Doc / Fix link to SS-2019-022 in changelogs
  docs/en/04_Changelogs/4.4.0.md
Labels: affects/v4, type/docs

#9077 fix #9075 log example yml-config in docs
  docs/en/02_Developer_Guides/07_Debugging/01_Error_Handling.md
Labels: affects/v4, type/docs

#9082 Fix of delimiter not used bug
  src/Dev/CsvBulkLoader.php
Labels: affects/mobile, change/patch

#7261 Remove `use_gzip` from HTMLEditorField since it's been removed by TinyMCE codebase
  docs/en/04_Changelogs/4.5.0.md
  src/Forms/HTMLEditor/HTMLEditorField.php
  src/Forms/HTMLEditor/TinyMCEGZIPGenerator.php
  tests/php/Forms/HTMLEditor/HTMLEditorFieldTest.php
Labels: affects/v4, change/minor, effort/easy, feedback-required/core-team, impact/low, type/enhancement

#9090 FIX Protect against undefined index when using nullifyEmpty option
  src/ORM/FieldType/DBString.php
Labels: affects/v4, change/patch

#9102 DOCS: Change default database connector.
  docs/en/00_Getting_Started/01_Installation/How_To/MySQL_SSL_Support.md
  docs/en/00_Getting_Started/03_Environment_Management.md
Labels: affects/v4, type/docs
