Repository silverstripe/silverstripe-framework, pull requests merged in 2020-04, with the labels that each got.

#9435 BUGFIX: Ensure diff arrays are one-dimensional
  src/View/Parsers/Diff.php
  tests/php/View/Parsers/DiffTest.php
Labels: affects/v4, change/patch

#9450 PHPUnit Fix last of deprecated function calls
  tests/php/Forms/HTMLEditor/HTMLEditorConfigTest.php
  tests/php/View/SSViewerTest.php
Labels: affects/v5, change/patch

#9447 [DOCS] Better debug text for errors generated by GridFieldDetailForm_ItemRequest
  composer.json
  lang/en.yml
  phpcs.xml.dist
  src/Forms/GridField/GridFieldDetailForm_ItemRequest.php
  src/Security/PasswordExpirationMiddleware.php
Labels: affects/v4, change/minor

#9432 Update MigrationTask class to be an abstract class
  src/Dev/MigrationTask.php
Labels: affects/v5, change/major

#9465 DOCS: Update to show default functionality of VersionedGridfieldDetailForm
  docs/en/02_Developer_Guides/00_Model/10_Versioning.md
Labels: affects/v4, change/patch, effort/easy, type/docs

#9458 DOC CMS 3.x file migration section about versioned files
  docs/en/02_Developer_Guides/14_Files/05_File_Migration.md
Labels: affects/v4, change/patch, effort/easy, type/docs

#9464 DOCS: Minor changes
  src/Forms/FormRequestHandler.php
  src/ORM/DataList.php
  src/Security/Permission.php
  tests/php/Forms/DatetimeFieldTest.php
Labels: affects/v4, change/patch, effort/easy, type/docs

#9454 NEW Allow InnoDB for FULLTEXT indexes
  docs/en/04_Changelogs/4.6.0.md
  src/ORM/Connect/MySQLDatabase.php
  src/ORM/Connect/MySQLSchemaManager.php
  src/ORM/Filters/FulltextFilter.php
  tests/php/ORM/DataObjectSchemaGenerationTest.php
  tests/php/ORM/Filters/FulltextFilterTest/TestObject.php
Labels: affects/v4, type/docs

#9461 Cache results of _configure_database.php glob
  _config/cache.yml
  src/Dev/Install/DatabaseAdapterRegistry.php
Labels: affects/v4, change/minor, type/enhancement

#9408 Add ClassInfo method to get all classes with a given extension applied
  src/Core/ClassInfo.php
  tests/php/Core/ClassInfoTest.php
  tests/php/Core/ClassInfoTest/BaseObject.php
  tests/php/Core/ClassInfoTest/ExtendTest.php
  tests/php/Core/ClassInfoTest/ExtendTest2.php
  tests/php/Core/ClassInfoTest/ExtendTest3.php
  tests/php/Core/ClassInfoTest/ExtensionTest1.php
  tests/php/Core/ClassInfoTest/ExtensionTest2.php
Labels: affects/v4, change/minor

#9494 DOCS Add Recipes section, add module version breakdown to 4.5.2
  docs/en/00_Getting_Started/05_Recipes.md
  docs/en/04_Changelogs/4.5.2.md
  docs/en/04_Changelogs/index.md
Labels: type/docs

#9497 Rename DBBigint.php for composer autoloading compatability
  src/ORM/FieldType/DBBigInt.php
Labels: affects/v4, change/patch

#9498 Update file paths for autoloading compatibility
  src/Control/Util/IPUtils.php
  tests/php/Forms/FormFactoryTest/EditFormFactory.php
  tests/php/Forms/FormRequestHandlerTest/TestFormRequestHandler.php
Labels: affects/v4, change/patch

#9501 DOCS: Fix typos & grammer
  docs/en/02_Developer_Guides/01_Templates/03_Requirements.md
  docs/en/02_Developer_Guides/14_Files/02_Images.md
  src/ORM/ArrayList.php
  src/ORM/DataList.php
  src/ORM/Filterable.php
  src/ORM/ListDecorator.php
  src/includes/constants.php
Labels: affects/v4, type/docs

#9425 DOC Document new in-modal file editing in changelogs
  docs/en/04_Changelogs/4.6.0.md
Labels: affects/v4, change/minor, effort/easy, type/docs
