Repository silverstripe/silverstripe-framework, pull requests merged in 2020-10, with the labels that each got.

#9707 ENH Replace E_USER_ERROR errors with exceptions
  docs/en/02_Developer_Guides/00_Model/05_Extending_DataObjects.md
  docs/en/02_Developer_Guides/07_Debugging/01_Error_Handling.md
  src/Control/Controller.php
  src/Control/HTTPRequest.php
  src/Control/RequestHandler.php
  src/Core/Extensible.php
  src/Dev/CsvBulkLoader.php
  src/Dev/SapphireTest.php
  src/Forms/CompositeField.php
  src/Forms/FieldList.php
  src/Forms/FormField.php
  src/Forms/SelectField.php
  src/Forms/TreeMultiselectField.php
  src/ORM/Connect/Database.php
  src/ORM/Connect/MySQLiConnector.php
  src/ORM/DataList.php
  src/ORM/DataObject.php
  src/ORM/FieldType/DBBoolean.php
  src/ORM/FieldType/DBDecimal.php
  src/ORM/FieldType/DBEnum.php
  src/ORM/FieldType/DBMultiEnum.php
  src/ORM/HasManyList.php
  src/ORM/Hierarchy/Hierarchy.php
  src/ORM/Map.php
  src/ORM/PolymorphicHasManyList.php
  src/ORM/Queries/SQLConditionalExpression.php
  src/ORM/UnsavedRelationList.php
  src/Security/Member_GroupSet.php
  src/Security/Permission.php
  src/View/Parsers/ShortcodeParser.php
  src/View/SSViewer_DataPresenter.php
  src/View/SSViewer_Scope.php
  tests/php/Control/HTTPRequestTest.php
  tests/php/Forms/CompositeFieldTest.php
Labels: affects/v4, change/minor

#9516 isLockedOut() in Member.php call LoginAttempt::getByEmail but it passes to it the unique_identifier_field instead $this->Email
  src/Security/Member.php
Labels: affects/v4, change/minor, effort/easy, impact/medium, type/enhancement

#9717 Update spaces in syntax, single quotes, early returns where possible
  src/ORM/Connect/DBConnector.php
  src/ORM/Connect/DBSchemaManager.php
  src/ORM/Connect/Database.php
  src/ORM/Connect/DatabaseException.php
  src/ORM/FieldType/DBBoolean.php
  src/ORM/FieldType/DBClassName.php
  src/ORM/FieldType/DBComposite.php
  src/ORM/FieldType/DBCurrency.php
  src/ORM/FieldType/DBDate.php
  src/ORM/FieldType/DBDatetime.php
  src/ORM/FieldType/DBDecimal.php
  src/ORM/FieldType/DBDouble.php
  src/ORM/FieldType/DBEnum.php
  src/ORM/FieldType/DBField.php
  src/ORM/FieldType/DBFloat.php
  src/ORM/FieldType/DBForeignKey.php
  src/ORM/FieldType/DBHTMLText.php
  src/ORM/FieldType/DBHTMLVarchar.php
  src/ORM/FieldType/DBIndexable.php
  src/ORM/FieldType/DBInt.php
  src/ORM/FieldType/DBLocale.php
  src/ORM/FieldType/DBMoney.php
  src/ORM/FieldType/DBMultiEnum.php
  src/ORM/FieldType/DBPolymorphicForeignKey.php
  src/ORM/FieldType/DBPrimaryKey.php
  src/ORM/FieldType/DBString.php
  src/ORM/FieldType/DBText.php
  src/ORM/FieldType/DBTime.php
  src/ORM/FieldType/DBVarchar.php
  src/ORM/FieldType/DBYear.php
Labels: affects/v4, change/minor

#9721 Allow setting sql_mode via config
  docs/en/00_Getting_Started/00_Server_Requirements.md
  docs/en/04_Changelogs/4.7.0.md
  src/ORM/Connect/MySQLDatabase.php
Labels: affects/v4, change/minor, impact/high, type/bug
