Repository silverstripe/silverstripe-framework, pull requests merged in 2020-03, with the labels that each got.

#9426 DOC Update atomic MigrationTask description
  src/Dev/MigrationTask.php
Labels: affects/v4, change/patch, effort/easy, impact/low, type/docs

#9434 [BUGFIX] silverstripe/admin is not required to be installed
  src/Security/CMSSecurity.php
Labels: affects/v4, change/patch

#9439 FIX Capitalisation fixes in welcome back message
  docs/en/02_Developer_Guides/01_Templates/02_Common_Variables.md
  docs/en/02_Developer_Guides/06_Testing/How_Tos/01_Write_a_FunctionalTest.md
  lang/en.yml
  src/Security/MemberAuthenticator/LoginHandler.php
Labels: affects/v4, change/patch

#9438 Add variadic URL parameter matches for url_handlers
  docs/en/02_Developer_Guides/02_Controllers/02_Routing.md
  src/Control/HTTPRequest.php
  tests/php/Control/HTTPRequestTest.php
Labels: affects/v4, change/minor

#9441 Remove sminee/phpunit-mock-objects from 5.x
  composer.json
Labels: affects/v5

#9442 CSV BOM stripping is now handled internally by league/csv
  src/Dev/CsvBulkLoader.php
  tests/php/Control/HTTPRequestTest.php
Labels: affects/v5

#9445 Added return type to ArraySubset constraint to be compatible with PHPUnit 9
  src/Dev/Constraint/ArraySubset.php
Labels: affects/v5, change/patch

#9446 Import correct ArraySubset class
  src/Dev/Constraint/ArraySubset.php
  src/Dev/SapphireTest.php
Labels: affects/v5, change/patch

#9448 [DOCS] Member::logInAs is not a valid example
  src/Security/Member.php
Labels: affects/v4, type/docs
