Repository silverstripe/silverstripe-framework, pull requests merged in 2020-08, with the labels that each got.

#9632 DOC Correct the example for getters/setters
  docs/en/02_Developer_Guides/00_Model/04_Data_Types_and_Casting.md
Labels: affects/v4, type/docs

#9633 BUG only use HTTPS link on the default controller template
  templates/SilverStripe/Control/Controller.ss
Labels: affects/v4, change/patch

#9642 PATCH: Prevents calling strpos with empty needle
  i18n/i18n.php
Labels: affects/v3, change/patch

#9643 Backport fix to GroupedDropdownFieldTest
  tests/php/Forms/GroupedDropdownFieldTest.php
Labels: affects/v4, change/patch

#9540 NEW: Improved task runner UI.
  client/styles/task-runner.css
  src/Dev/TaskRunner.php
  templates/SilverStripe/Dev/TaskRunner.ss
Labels: impact/low, type/UX, type/enhancement, type/frontend

#9653 Update 05_Coding_Conventions.md
  docs/en/00_Getting_Started/05_Coding_Conventions.md
Labels: affects/v3, type/docs

#9542 #3236 Added dev/config view
  _config/dev.yml
  docs/en/02_Developer_Guides/07_Debugging/02_URL_Variable_Tools.md
  src/Dev/DevConfigController.php
Labels: affects/v4, feedback-required/core-team
