Repository silverstripe/silverstripe-framework, pull requests merged in 2020-09, with the labels that each got.

#8915 NEW DataQuery::exists now generates EXISTS SQL statements
  src/ORM/DataList.php
  src/ORM/DataQuery.php
  tests/php/ORM/DataQueryTest.php
Labels: affects/v4, change/minor

#9650 Added exception for enumerated array (#9644)
  src/View/ArrayData.php
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/bug

#9569 ModuleManifest::getModuleByPath fix to ensure right module is returned
  src/Core/Manifest/ModuleManifest.php
  tests/php/Core/Manifest/ClassManifestTest.php
  tests/php/Core/Manifest/ModuleManifestTest.php
  tests/php/Core/Manifest/fixtures/classmanifest/vendor/silverstripe/modulecbetter/_config/config.yml
  tests/php/Core/Manifest/fixtures/classmanifest/vendor/silverstripe/modulecbetter/client/script.js
  tests/php/Core/Manifest/fixtures/classmanifest/vendor/silverstripe/modulecbetter/code/VendorClassX.php
  tests/php/Core/Manifest/fixtures/classmanifest/vendor/silverstripe/modulecbetter/composer.json
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug

#9660 DOCS Add triage resources, document stale PR definition
  docs/en/05_Contributing/01_Code.md
  docs/en/05_Contributing/15_Triage_Resources.md
Labels: affects/v4, change/minor, effort/easy, feedback-required/core-team, impact/medium, type/docs

#9280 DOC Update breadcrumb template in theme rather than app.
  docs/en/02_Developer_Guides/01_Templates/02_Common_Variables.md
Labels: affects/v4, change/minor, effort/easy, impact/low, type/docs

#9552 Added a tip to docs describing how to set a cookie for less than a day
  docs/en/02_Developer_Guides/18_Cookies_And_Sessions/01_Cookies.md
  src/Control/Cookie.php
  src/Control/CookieJar.php
  src/Control/Cookie_Backend.php
Labels: affects/v4, change/minor, effort/easy, impact/low, type/docs

#9678 FIX Problem with direct compare in SELECT statement causing incompatibility with SQL Server database
  src/ORM/FieldType/DBForeignKey.php
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug

#9681 BUG Make PasswordEncryptor::check more resistent to timing attacks
  src/Security/PasswordEncryptor.php
Labels: affects/v4, change/patch

#9634 BUG Use proper ellipsis character in the various summary method.
  src/ORM/FieldType/DBString.php
  src/ORM/FieldType/DBText.php
  tests/php/ORM/DBFieldTest.php
  tests/php/ORM/DBHTMLTextTest.php
  tests/php/ORM/DBTextTest.php
Labels: affects/v4, change/patch, effort/easy, impact/medium, type/bug

#9604 BUG Resolve issue where TreeMultiSelectField would error loading its value
  src/Forms/TreeMultiselectField.php
  tests/php/Forms/TreeMultiselectFieldTest.php
Labels: affects/v4, change/patch, effort/medium, impact/high, type/bug

#9670 HistoryViewer: explain "magic names"
  docs/en/02_Developer_Guides/00_Model/10_Versioning.md
Labels: affects/v4, change/minor, effort/easy, impact/low, type/docs

#9649 FIX: Include missing security page titles when CMS not installed (fixes #9648)
  src/Security/Security.php
Labels: affects/v4, change/patch, effort/easy, impact/high, type/bug

#8846 Template parser bugs
  src/View/SSTemplateParser.peg
  src/View/SSTemplateParser.php
  tests/php/View/SSViewerTest.php
Labels: affects/v4, change/patch, effort/medium, impact/medium, type/bug

#9682 DOCS: Example of partial cache expiry setting.
  docs/en/02_Developer_Guides/01_Templates/11_Partial_Template_Caching.md
Labels: affects/v4, type/docs

#9626 DOC Add process for releasing individual module patches
  docs/en/05_Contributing/05_Making_A_SilverStripe_Core_Release.md
Labels: affects/v4, change/minor, effort/easy, impact/medium, type/docs

#9710 #9706: Updated doc for case-sensitive filter
  docs/en/02_Developer_Guides/00_Model/06_SearchFilters.md
Labels: affects/v4, type/docs

#9714 FIX Fix namespace parsing under PHP 8, tweak readability of parser
  src/Core/ClassInfo.php
  tests/php/Core/ClassInfoTest.php
Labels: affects/v4, effort/easy, impact/high, type/bug
