Repository silverstripe/silverstripe-framework, pull requests merged in 2020-02, with the labels that each got.

#9385 Updated the "Template Syntax" Documentation
  docs/en/02_Developer_Guides/01_Templates/01_Syntax.md
Labels: affects/v4, type/docs

#9397 FIX Update ORM DBField types to use Injector in scaffoldFormField()
  src/ORM/FieldType/DBBoolean.php
  src/ORM/FieldType/DBHTMLText.php
  src/ORM/FieldType/DBInt.php
  src/ORM/FieldType/DBText.php
  src/ORM/FieldType/DBYear.php
Labels: affects/v4, change/patch

#9223 DOCS Web worker concurrency caveats
  docs/en/00_Getting_Started/00_Server_Requirements.md
Labels: affects/v4, type/docs

#8987 API TestSession request methods now use the correct HTTP method
  docs/en/02_Developer_Guides/06_Testing/01_Functional_Testing.md
  src/Dev/TestSession.php
Labels: affects/v4, feedback-required/core-team

#8838 Use '/' as an alternative designation for root in routing
  docs/en/02_Developer_Guides/02_Controllers/02_Routing.md
  src/Control/HTTPRequest.php
  tests/php/Control/ControllerTest.php
  tests/php/Control/RequestHandlingTest/HTTPMethodTestController.php
  tests/php/Control/RequestHandlingTest/TestFormHandler.php
Labels: affects/v4, change/patch

#9412 Update Travis config to use stable PHP 7.4 release
  .travis.yml
Labels: affects/v4, change/patch
