Repository silverstripe/silverstripe-framework, pull requests merged in 2021-05, with the labels that each got.

#9631 FIX Retain custom sort on custom lists in GridFieldAddExistingAutoCompleter
  src/Forms/GridField/GridFieldAddExistingAutocompleter.php
  tests/php/Forms/GridField/GridFieldAddExistingAutocompleterTest.php
Labels: affects/v4, change/minor, effort/easy, impact/medium, type/enhancement

#9192 NEW: Support dot syntax in form field names
  docs/en/02_Developer_Guides/03_Forms/00_Introduction.md
  docs/en/02_Developer_Guides/03_Forms/How_Tos/06_Handle_Nested_data.md
  docs/en/04_Changelogs/4.9.0.md
  src/Forms/FieldList.php
  src/Forms/Form.php
  src/Forms/FormField.php
  src/Forms/FormTemplateHelper.php
  src/ORM/DataObject.php
  tests/php/Forms/FormTest.php
Labels: affects/v4, change/minor, effort/medium, feedback-required/author, impact/low, type/enhancement

#9655 NEW: Add GridFieldDetailForm::setRedirectMissingRecords()
  src/Forms/GridField/GridFieldDetailForm.php
  src/Forms/GridField/GridFieldDetailForm_ItemRequest.php
  tests/php/Forms/GridField/GridFieldDetailFormTest.php
  tests/php/Forms/GridField/GridFieldDetailFormTest.yml
  tests/php/Forms/GridField/GridFieldDetailFormTest/CategoryController.php
  tests/php/Forms/GridField/GridFieldDetailFormTest/Person.php
  tests/php/Forms/GridField/GridFieldDetailFormTest/TestController.php
Labels: affects/v4, change/minor, effort/medium, impact/medium, type/enhancement
